---
title: "R Notebook"
output: html_notebook
---

```{r}
library(ggplot2)
cbPalette <- c("#1b9e77", "#d95f02", "#e7298a")
```

```{r}
df <- read.csv('hk_results.csv')
df2 <- read.csv('validation_results.csv')
df3 <- read.csv('emobank_results.csv')
```

```{r}
ggplot(df, aes(x=contrast, y=treatment)) + 
  geom_point(aes(color=distribution), position=ggstance::position_dodgev(height=0.3)) +
  geom_errorbar(aes(xmin=lower, xmax=upper, color=distribution),
                position=ggstance::position_dodgev(height=0.3),
                width=0.25) +
  geom_vline(xintercept=0, linetype=3) +
  # ggtitle('Effects of language attributes on opinions of 2019 HK protests') + 
  theme_minimal() +
  scale_colour_manual(values=cbPalette) +
  # scale_colour_discrete(breaks=c('randomization', 'transported', 'target')) + 
  theme(legend.position='top', axis.title.y=element_blank(), plot.title = element_text(hjust = 0.5),
        axis.text=element_text(size=14), legend.title=element_text(size=16), legend.text=element_text(size=14), axis.title.x=element_text(size=16))

ggsave('hk_results.png')
  # theme(axis.text=element_text(size=14), axis.title=element_text(size=14))
```

```{r}
df2$method <- factor(df2$method, levels=c("amazon_clf", "emobank_clf", "emobank_lm"),
                     labels=c("Amazon\nclassification", "EmoBank\nclassification", "EmoBank\nlanguage\n modeling"))
ggplot(df2, aes(x=response, y=method)) + 
  geom_point(aes(color=distribution), position=ggstance::position_dodgev(height=0.3)) +
  geom_errorbar(aes(xmin=lower, xmax=upper, color=distribution),
                position=ggstance::position_dodgev(height=0.3),
                width=0.25) +
  facet_wrap(~method, ncol=1, scales='free') +
  # theme(axis.text.y=element_blank(), axis.ticks.y=element_blank(), strip.text.y=element_blank(),
  #       strip.text.x=element_blank(), strip.background = element_blank()) + 
  # ggtitle('Validation of transported responses') + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme_minimal() +
  scale_colour_manual(values=cbPalette, breaks=c('randomization', 'transported', 'target')) +
  theme(legend.position='top', strip.text=element_blank(), axis.title.y=element_blank(),
        axis.text=element_text(size=14), legend.title=element_text(size=16), legend.text=element_text(size=14), axis.title.x=element_text(size=16))

ggsave('validation_results.png', width=7.29, height=4)
```

```{r}
ggplot(df3, aes(x=contrast, y=treatment)) + 
  geom_point(aes(color=distribution), position=ggstance::position_dodgev(height=0.3)) +
  geom_errorbar(aes(xmin=lower, xmax=upper, color=distribution),
                position=ggstance::position_dodgev(height=0.3),
                width=0.25) +
  geom_vline(xintercept=0, linetype=3) +
  # ggtitle('Effects of language attributes on opinions of 2019 HK protests') + 
  theme_minimal() +
  scale_colour_manual(values=cbPalette) +
  # scale_colour_discrete(breaks=c('randomization', 'transported', 'target')) + 
  theme(legend.position='top', axis.title.y=element_blank(), plot.title = element_text(hjust = 0.5),
        axis.text=element_text(size=14), legend.title=element_text(size=16), legend.text=element_text(size=14), axis.title.x=element_text(size=16))

ggsave('emobank_results.png', width=7.29, height=3)
```

